### ISSUE TITLE
Expose Symfony debug commands through Makefile

### ISSUE THREAD

**Issue by brankol** [sigwinhq/yassg#56]
Symfony has useful debug commands like:

- debug/router
- debug/translation
- debug/twig

However, in order to call them, one has to prefix them with the yassg executable like `vendor/sigwin/yassg/bin/yassg debug:translation de`. This is hard to remember, and not easily discoverable.

Therefore, it would be nice to have these commands aliased using `make`:
`make debug/router`

Also, by adding them to `make help`, these commands would not need to be remembered.

**Comment by dkarlovi** [comment]
This might be redundant if we do #57.

**Comment by dkarlovi** [comment]
We enabled Symfony profiler toolbar  #60, this task is probably obsoleted by it. Closing here until proven otherwise.
